version: "3.8"

services:
  backend:
    container_name: mhfr-backend
    image: kuunika/mhfr-backend
    depends_on:
      - database
    ports:
      - 4000:4000
    env_file:
      - ./.env

  client:
    container_name: mhfr-frontend
    image: kuunika/mhfr-frontend
    depends_on:
      - backend
    ports:
      - 8888:80
    env_file:
      - ./.env

  database:
    container_name: mhfr-database
    image: kuunika/mhfr-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mhfr_mysql:/var/lib/mysql
volumes:
  mhfr_mysql:
